version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.dockerfile
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    env_file: 
      - ./.env
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${BACKEND_PORT}
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.dockerfile
    ports:
      - "${FRONTEND_PORT:-3000}:80" 
    env_file: 
      - ./frontend/.env
    volumes:
      - ./frontend:/app # Only mount for development purposes
    depends_on:
      - backend
    networks:
      - app-network

  mongodb:
    image: mongo:5
    environment:
      MONGO_INITDB_DATABASE: surge-social
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
